<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BackAndre.Application\BackAndre.Application.csproj" />
    <ProjectReference Include="..\BackAndre.Domain\BackAndre.Domain.csproj" />
    <ProjectReference Include="..\BackAndre.Infrastructure\BackAndre.Infrastructure.csproj" />
  </ItemGroup>
</Project>
