<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BackAndre.Domain\BackAndre.Domain.csproj" />
    <ProjectReference Include="..\BackAndre.Infrastructure\BackAndre.Infrastructure.csproj" />
  </ItemGroup>
</Project>
